@startuml
title Temptasty - temperature samples

  database "DB (InfluxDB)" {
    frame "temp_samples" {
      component comp1 [
        unit:    string
        name: string
        time:   dateTime:RFC3339
        value: double
      ]
    }
  }
  node "reverse proxy (nginx)" {
    [backend (Quarkus)] as backend
    [frontend (Angular)] as frontend
    frontend -> backend : https
  }

  [Browser] --> frontend : https
  [backend] --> comp1
  [Sensor2] --> backend : https
  [Sensor1] --> backend : https

@enduml
